###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: cqrs-ride-share-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=cqrs-ride-share
        - MYSQL_USER=cqrs-ride-share
        - MYSQL_PASSWORD=demo
      ports:
        - "33060:3306"

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
      container_name: cqrs-ride-share-elasticsearch
      ports:
        - 9200:9200

    webserver:
      image: nginx:alpine
      container_name: cqrs-ride-share-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: cqrs-ride-share-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

