# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    RideShare\Infrastructure\:
        resource: '../../src/RideShare/Infrastructure/'

    RideShare\Infrastructure\Ui\Web\:
        resource: '../../src/RideShare/Infrastructure/Ui/Web/'
        public: true

    # Handlers
    RideShare\Application\RegisterRide\RegisterRideHandler:
        class: RideShare\Application\RegisterRide\RegisterRideHandler
        public: true
        tags:
          - { name: command_handler, handles: RideShare\Application\RegisterRide\RegisterRideCommand }

    RideShare\Application\ChangeDepartureTime\ChangeDepartureTimeHandler:
        class: RideShare\Application\ChangeDepartureTime\ChangeDepartureTimeHandler
        public: true
        tags:
          - { name: command_handler, handles: RideShare\Application\ChangeDepartureTime\ChangeDepartureTimeCommand }


    # Projections
    RideShare\Infrastructure\Projection\Projector:
        class: RideShare\Infrastructure\Projection\Projector
        calls:
          - method: register
            arguments:
              -
                - '@RideShare\Infrastructure\Projection\RideWasCreatedProjection'
                - '@RideShare\Infrastructure\Projection\DepartureTimeHasChangedProjection'


    # Domain events
    RideShare\Infrastructure\Events\PersistDomainEventSubscribe:
        public: true

    Elasticsearch\Client:
      factory: [Elasticsearch\ClientBuilder, fromConfig]
      arguments:
          - hosts:
              - '%elastic_search%'