# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    RideShare\Infrastructure\:
        resource: '../../src/RideShare/Infrastructure/*'

    # Handlers
    RideShare\Application\RegisterRide\RegisterRideHandler:
        class: RideShare\Application\RegisterRide\RegisterRideHandler
        public: true
        tags:
          - { name: command_handler, handles: RideShare\Application\RegisterRide\RegisterRideCommand }


    # Projections
    RideShare\Infrastructure\Projection\Projector:
        class: RideShare\Infrastructure\Projection\Projector
        calls:
          - method: register
            arguments:
              -
                - '@RideShare\Infrastructure\Projection\DoctrineDbal\RideWasCreatedProjection'


    # Domain events
    RideShare\Infrastructure\Events\PersistDomainEventSubscribe:
        public: true