RideShare\Domain\Core\Entities\StoredEvent:
  type: entity
  table: event
  id:
    id:
      type: integer
      generator:
        strategy: auto
  fields:
    event:
      type: string
    occurredOn:
      type: datetime
    body:
      type: text